title: Feira do Bem
description: Site e blog da Feira do Bem, em Rondonópolis.
baseurl: ""  # geralmente vazio para GitHub Pages no domínio padrão
url: "https://maysilvalps.github.io/feira-do-bem"  # substitua com seu URL real

theme: minima  # tema simples e oficial do Jekyll, você pode mudar depois se quiser

plugins:
  - jekyll-feed

paginate: 5  # posts por página, se usar paginação
